### ISSUE TITLE
Fedora notifications (messages) contain very long subject

### ISSUE THREAD

**Issue by dschwoerer** [fedora-copr/copr#3493]
I just got a mail from copr via fedora notifications with the following subject:
```
Subject: [Copr] <bound method BuildChrootStarted.summary of
 BuildChrootStartedV1(id='702cc3bd-450e-44bb-82cf-b92ba4a67e11',
 topic='org.fedoraproject.prod.copr.build.start', body={'user': 'davidsch',
 'copr': 'fixes4bout', 'owner': 'davidsch', 'pkg': None, 'build': 8190255,
 'chroot': 'srpm-builds', 'version': None, 'status': 3, 'ip':
 'xxxxx, 'who':
 'backend.worker-rpm_build_worker:xxxx', 'pid': xxxx, 'what': 'build
 start: user:davidsch copr:fixes4bout pkg:None build:xxxxx
 ip:xxxxx pid:14xxxx'})>
```
22 days ago, the subject was:
`[Copr] org.fedoraproject.prod.copr.build.end`

While the old subject was maybe a bit short, the new one is probably not what was intended.

I hope this is the correct place to report this.

**Comment by nikromen** [comment]
Hi, this is 100% a bug, thanks for the report!

my guess is this was introduced by 1559b850

**Comment by praiskup** [comment]
Probably related to: 
https://github.com/fedora-copr/copr/pull/3344#discussion_r1770988337

**Comment by decathorpe** [comment]
This was marked as `done` but I'm today still getting notifcations like `[Copr] <bound method BuildChrootEnded.summary of BuildChrootEndedV1(id='68574eaf-a26a-443e-aaef-86c576c00f4e', topic='[org.fedoraproject.prod.copr.build](http://org.fedoraproject.prod.copr.build/).end', body={'user': 'decathorpe', 'copr': 'rbspy-updates', 'owner': 'decathorpe', 'pkg': 'rust-proc-maps', 'build': 8654814, 'chroot': 'fedora-rawhide-aarch64', 'version': '0.4.0-1', 'status': 1, 'ip': '54.226.186.132', 'who': 'backend.worker-rpm_build_worker:8654814-fedora-rawhide-aarch64', 'pid': 2878942, 'what': 'build end: user:decathorpe copr:rbspy-updates build:8654814 pkg:rust-proc-maps version:0.4.0-1 ip:54.226.186.132 pid:2878942 status:1'})>` ... has the fix not been deployed yet?

**Comment by nikromen** [comment]
Hi @decathorpe the fix is it the main branch, yes. But the're wasn't Copr release since 22 Oct 2024, so the fix wasn't deployed yet. But since this was a relatively small change, I can hot-fix it for you in production, if you need it fixed. Next copr release should be soon (We do release in 3-4 months window so we'll do next one soon)

**Comment by decathorpe** [comment]
Ok, so if this was fixed in Nov 28, 2024 and there's releases every 3-4 months, I can wait for that 😅

**Comment by decathorpe** [comment]
Any updates here? It's three more months and the notifications from COPR are still ... well, broken

**Comment by FrostyX** [comment]
Thank you for the bump @decathorpe,

as I understand the previous comments, this should already be fixed in the upstream and is just waiting for a release. The problem is, a release already happened - https://docs.pagure.org/copr.copr/release-notes/2025-03-26.html

I am reopening the issue then.

**Comment by decathorpe** [comment]
Thanks! As far as I can tell, it *should* have been fixed, but actually wasn't and the issue is still present :(

**Comment by nikromen** [comment]
so this is a bit unfortunate... the fix works and it is deployed on staging instance, see the staging datagrepper:

![Image](https://github.com/user-attachments/assets/d307926b-9b9b-4632-92bd-95dfed0be314)

but it seems like the old version is still present on production, despite the fact that we have new version of copr-messaging deployed at backend... I tried to restart copr-backend services but without any success - any changes that are applied aren't actually "used"...

@fedora-copr/copr-team do you have an idea how to force the copr-messaging to restart/apply the changes in code? Basically what I need is to refresh these class instances https://github.com/fedora-copr/copr/blob/abd055f968c83fb37b21f678c71e3c6472f2a8e5/backend/copr_backend/msgbus.py#L57 in memory (and I want to really avoid restarting the machine for this)

**Comment by decathorpe** [comment]
Looks like this is still not fixed ... this is a Matrix notification from today:

```
[Copr] <bound method BuildChrootStarted.summary of BuildChrootStartedV1(id='372f2d52-89c7-4fce-862e-6046a0bcac7a', topic='[org.fedoraproject.prod.copr.build](http://org.fedoraproject.prod.copr.build/).start', body={'user': 'decathorpe', 'copr': 'openssl-3.5.0-for-testing-only', 'owner': 'decathorpe', 'pkg': 'openssl', 'build': 9101044, 'chroot': 'fedora-42-s390x', 'version': '1:3.5.0-3', 'status': 3, 'ip': '13.121.95.254', 'who': 'backend.worker-rpm_build_worker:9101044-fedora-42-s390x', 'pid': 1819851, 'what': 'build start: user:decathorpe copr:openssl-3.5.0-for-testing-only pkg:openssl build:9101044 ip:13.121.95.254 pid:1819851'})>
```

**Comment by nikromen** [comment]
ahh, so it seems like the python3-copr-messaging-1.1-1 should be updated in multiple places... but I have no idea where this package is deployed in the fedora infrastructure, as I can't see it and I don't have access rights to it

**Comment by nikromen** [comment]
@abompard do you have any idea where else copr-messaging needs to be updated in fedora infrastructure?

**Comment by abompard** [comment]
The apps that use all the schemas are:
- datanommer.models
- datagrepper
- fmn
- fedbadges

The Matrix notification is probably coming from FMN.

**Comment by nikromen** [comment]
I see... do you have the rights to update the python3-copr-messaging package in the service? Could you please do it if so? :)

**Comment by praiskup** [comment]
Seems like @nikromen is still communicating this with infra folks.  Can we really have this closed?

**Comment by abompard** [comment]
It's updated :-)

**Comment by nikromen** [comment]
Thank you <3 @decathorpe could you confirm it's working now?

**Comment by decathorpe** [comment]
It's better now, though still hella weird:

`[Copr] Copr Message in project "decathorpe/aws-lc-rs": build 9137379: chroot "fedora-rawhide-x86_64" ended as "succeeded". `

Why does it tell me that it's a "Copr Message"? lol that's redundant twice ...

**Comment by abompard** [comment]
> Why does it tell me that it's a "Copr Message"? lol that's redundant twice ...

I think the reason is here: https://github.com/fedora-copr/copr/blob/4221580a0fe1d30116e5841ff5eafe27bf9baead/messaging/copr_messaging/private/hierarchy.py#L42

**Comment by praiskup** [comment]
> lol that's redundant twice ...

😅 indeed, would you open a PR fixing this? (or at least a separate issue)
